# Generated by Django 3.2.13 on 2022-05-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
